<a href="https://colab.research.google.com/github/SHEHAN-120/gmail-spam-detector-nlp/blob/main/nlp_spam_detection_bow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('spam.csv')

In [3]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
df.Category.value_counts()/len(df)*100

Category
ham     86.593683
spam    13.406317
Name: count, dtype: float64

In [6]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [7]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
new_df=pd.read_csv('spam.csv')

In [9]:
new_df['Category'].replace({'ham':0,'spam':1},inplace=True)

/tmp/ipython-input-9-1471673109.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df['Category'].replace({'ham':0,'spam':1},inplace=True)
/tmp/ipython-input-9-1471673109.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_df['Category'].replace({'ham':0,'spam':1},inplace=True)


In [10]:
new_df.head()

Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [11]:
df.shape

(5572, 3)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [14]:
X_train.shape

(4457,)

In [15]:
X_test.shape

(1115,)

In [16]:
X_train[:4]

4807          Call me when u finish then i come n pick u.
3580    Multiply the numbers independently and count d...
2502                         No da..today also i forgot..
4102    GSOH? Good with SPAM the ladies?U could b a ma...
Name: Message, dtype: object

In [17]:
y_train[:4]

4807    0
3580    0
2502    0
4102    1
Name: spam, dtype: int64

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
v=CountVectorizer()
X_train_cv=v.fit_transform(X_train.values)
X_train_cv
X_test_cv=v.transform(X_test)

In [20]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [21]:
X_train_cv.shape

(4457, 7720)

In [22]:
v.get_feature_names_out()[1000]

'anyones'

In [23]:
v.vocabulary_

{'call': 1616,
 'me': 4378,
 'when': 7455,
 'finish': 2865,
 'then': 6796,
 'come': 1914,
 'pick': 5176,
 'multiply': 4612,
 'the': 6783,
 'numbers': 4833,
 'independently': 3658,
 'and': 963,
 'count': 2037,
 'decimal': 2213,
 'points': 5265,
 'for': 2948,
 'division': 2371,
 'push': 5482,
 'places': 5206,
 'like': 4095,
 'showed': 6095,
 'you': 7684,
 'no': 4775,
 'da': 2151,
 'today': 6911,
 'also': 927,
 'forgot': 2961,
 'gsoh': 3265,
 'good': 3190,
 'with': 7523,
 'spam': 6316,
 'ladies': 3979,
 'could': 2034,
 'male': 4308,
 'gigolo': 3139,
 'join': 3825,
 'uk': 7093,
 'fastest': 2790,
 'growing': 3258,
 'mens': 4413,
 'club': 1866,
 'reply': 5687,
 'oncall': 4912,
 'mjzgroup': 4496,
 '08714342399': 117,
 '2stop': 416,
 'stop': 6461,
 'msg': 4588,
 '50rcvd': 550,
 'do': 2379,
 'thought': 6837,
 'put': 5486,
 'it': 3753,
 'back': 1195,
 'in': 3638,
 'box': 1463,
 'ur': 7173,
 'chance': 1730,
 'to': 6907,
 'win': 7497,
 '250': 374,
 'cash': 1686,
 'every': 2678,
 'wk': 7532,
 'txt'

In [24]:
X_train_np=X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [25]:
np.where(X_train_np[0]!=0)

(array([1616, 1914, 2865, 4378, 5176, 6796, 7455]),)

In [26]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [27]:
y_pred=model.predict(X_test_cv)

In [28]:
y_pred

array([0, 0, 1, ..., 0, 0, 1])

In [29]:
from sklearn.metrics import classification_report

In [30]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       971
           1       0.98      0.91      0.94       144

    accuracy                           0.99      1115
   macro avg       0.98      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115



## Sample Check (Attached image)

In [31]:
message={"10 resume mistakes hiring managers notice instantly"}

In [32]:
print(message)

{'10 resume mistakes hiring managers notice instantly'}


In [33]:
msg_cnt=v.transform(message)
model.predict(msg_cnt)

array([1])